# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 06:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=800)),
                ('images', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_my_subclass', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipe.Post')),
                ('collaborative', models.BooleanField()),
                ('entries', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            bases=('recipe.post',),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipe.Post')),
                ('ingredients', django.contrib.postgres.fields.jsonb.JSONField()),
                ('steps', django.contrib.postgres.fields.jsonb.JSONField()),
                ('portions', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('recipe.post',),
        ),
    ]
